// <auto-generated />
using System;
using CloupardTask.Api.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloupardTask.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250107115611_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CloupardTask.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gadgets and devices",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Men's and Women's Wear",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fiction and Non-Fiction",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A selection of packaged items grouped together for convenience and value. Perfect for customers looking for multiple products at once.",
                            Name = "BUNDLES"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A variety of fresh, dried, and aromatic herbs that enhance the flavor of dishes and offer natural remedies.",
                            Name = "HERBS"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A wide assortment of fresh, seasonal, and nutrient-rich vegetables, including leafy greens, root vegetables, and more.",
                            Name = "VEGETABLES"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Essential products for everyday use, ranging from gardening tools to home and office supplies.",
                            Name = "SUPPLIES"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A colorful collection of fresh-cut flowers for any occasion, designed to bring beauty and fragrance into your home or special event.",
                            Name = "FLOWERS"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Fresh, juicy, and seasonal fruits picked to provide the best taste and nutrition, perfect for snacking or adding to meals.",
                            Name = "FRUITS"
                        });
                });

            modelBuilder.Entity("CloupardTask.Domain.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CloupardTask.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CloupardTask.Domain.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("CloupardTask.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "The iPhone 16 Pro Max offers cutting-edge performance, stunning visuals, and an exceptional camera experience. With its 6.7-inch OLED display, this device is perfect for gaming, content creation, and all your daily tasks.",
                            ImageUrl = "Images\\phone.webp",
                            Name = "iPhone 16 Pro Max - Premium Smartphone",
                            Price = 1500.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "The MacBook Pro M2 features Apple's powerful M2 chip, offering top-notch performance for professional and creative work. Its 13-inch Retina display and long battery life make it the perfect companion for productivity on the go.",
                            ImageUrl = "Images\\macbook.webp",
                            Name = "MacBook Pro M2 - High-Performance Laptop",
                            Price = 1199.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "A timeless essential for any wardrobe, this Classic White T-Shirt is made from soft, breathable cotton and provides all-day comfort. Whether you're lounging at home or going out with friends, it's a must-have for casual looks.",
                            ImageUrl = "Images\\tsh.webp",
                            Name = "Classic White T-Shirt - Casual Comfort",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "The Great Gatsby is a captivating story of love, wealth, and tragedy set in the Roaring Twenties. F. Scott Fitzgerald's classic novel explores the American Dream and its complexities through the eyes of Nick Carraway and the enigmatic Jay Gatsby.",
                            ImageUrl = "Images\\novell.webp",
                            Name = "The Great Gatsby by F. Scott Fitzgerald - Classic Novel",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "1984 by George Orwell is a gripping, thought-provoking dystopian novel that critiques totalitarianism and explores themes of surveillance, freedom, and individuality. Set in a society under constant surveillance, the story follows Winston Smith as he rebels against the oppressive regime.",
                            ImageUrl = "Images\\1984.jpg",
                            Name = "1984 by George Orwell - Dystopian Masterpiece",
                            Price = 9.99m
                        });
                });

            modelBuilder.Entity("CloupardTask.Domain.Models.Order", b =>
                {
                    b.HasOne("CloupardTask.Domain.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CloupardTask.Domain.Models.OrderDetail", b =>
                {
                    b.HasOne("CloupardTask.Domain.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloupardTask.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CloupardTask.Domain.Models.Product", b =>
                {
                    b.HasOne("CloupardTask.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CloupardTask.Domain.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CloupardTask.Domain.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CloupardTask.Domain.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
