name: CI/CD Pipeline for Windows Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' # Adjust to your .NET version

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release -o ./publish

    - name: Deploy to Windows Server
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: ./publish/
        target: C:/inetpub/wwwroot/your-app # IIS root folder
